name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: [4.5, 5.0]
              os: [macos-latest, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v4

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "latest"
            
            - name: Install
              run: |
                uv sync  --all-extras --dev
                uv pip install bpy~=${{ matrix.version }}
            
            - name: Run tests
              run: |
                uv run -m pytest -vv --cov=nodebpy --cov-report=xml
    
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              if: matrix.os == 'macos-latest' && matrix.version == '5.0'
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                name: coverage.xml

            - name: Upload coverage reports to Codecov
              if: matrix.os == 'macos-latest' && matrix.version == '5.0'
              uses: codecov/codecov-action@v3
    
